### Creating one dimensional Numpy array(vector)

In [2]:
import numpy as np

In [9]:
np.array([1,2,3,4,5,6])


array([1, 2, 3, 4, 5, 6])

In [14]:
A=np.array([1,2,3,4,5,6]) 
print(A) 

[1 2 3 4 5 6]


In [12]:
type(A)

numpy.ndarray

### Creating two dimensional numpy array(Matrix)

In [16]:
Matrix=np.array([1,2,3],[4,5,6]) 


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [18]:
Matrix=np.array([[1,2,3],[4,5,6]]) 
Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
type(Matrix)

numpy.ndarray

In [20]:
Matrix=np.array([[1,2,3],[4,5,6,7]]) 
Matrix

C:\Users\DELL\AppData\Local\Temp\ipykernel_12756\3270415444.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  Matrix=np.array([[1,2,3],[4,5,6,7]])


array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [21]:
Matrix=np.array([1,2,3],dtype=float) 
Matrix

array([1., 2., 3.])

In [23]:
Matrix=np.array([1,2,3],dtype=bool) 
Matrix

array([ True,  True,  True])

In [24]:
Matrix=np.array([1,2,0],dtype=bool) 
Matrix

array([ True,  True, False])

In [25]:
Matrix=np.array([1,2,0],dtype=complex) 
Matrix

array([1.+0.j, 2.+0.j, 0.+0.j])

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,3)

array([1, 4, 7])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.zeros([3,4],int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
np.ones([3,4],int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
np.random.rand(2,2)

array([[0.89693684, 0.31439446],
       [0.85303397, 0.83443493]])

In [40]:
np.random.randn(3,2)

array([[-0.50692771, -0.83933631],
       [ 1.44603782,  0.79211662],
       [-0.27572744,  0.12982545]])

In [57]:
np.random.randint(3,50,10)

array([ 7, 25,  7,  4, 14, 44, 33, 15, 14, 47])

In [64]:
np.linspace(0,2,4,dtype=int)

array([0, 0, 1, 2])

In [68]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [72]:
np.identity(2,int)

array([[1, 0],
       [0, 1]])

In [73]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a2=np.arange(0,10,float)
a2

TypeError: unsupported operand type(s) for /: 'int' and 'type'

In [75]:
a2=np.arange(0,10,dtype=float)
a2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
a2.reshape(2,5)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [83]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [86]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
a1.ndim

1

In [88]:
a2.ndim

1

In [89]:
a3.ndim

3

In [90]:
a1.shape

(10,)

In [91]:
a3.shape

(3, 3, 3)

In [92]:
a2.shape

(10,)

In [93]:
a2.size

10

In [94]:
a3.size

27

### Changing Data type

In [95]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [97]:
x.astype(float)

array([1., 2., 3., 4.])

In [98]:
y=np.arange(12).reshape(4,3)
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
y+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [100]:
y*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [101]:
y-5

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [102]:
y/2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [103]:
y**2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]], dtype=int32)

In [104]:
y//2

array([[0, 0, 1],
       [1, 2, 2],
       [3, 3, 4],
       [4, 5, 5]], dtype=int32)

In [105]:
y%2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [107]:
b=np.arange(12).reshape(2,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [108]:
b>2

array([[False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [109]:
b<2

array([[ True,  True, False, False, False, False],
       [False, False, False, False, False, False]])

In [110]:
b=2

In [111]:
y+b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [112]:
y-b

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [113]:
y/b

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [114]:
y*b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [115]:
y%b

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [116]:
y//b

array([[0, 0, 1],
       [1, 2, 2],
       [3, 3, 4],
       [4, 5, 5]], dtype=int32)

In [119]:
c=np.random.random((3,3))
c

array([[0.31027793, 0.94578958, 0.80736274],
       [0.21739658, 0.8238593 , 0.48643005],
       [0.03550226, 0.05447605, 0.44842672]])

In [121]:
a=np.round(c*100)
a

array([[31., 95., 81.],
       [22., 82., 49.],
       [ 4.,  5., 45.]])

In [122]:
a.max()

95.0

In [123]:
a.min()

4.0

In [124]:
a.sum()

414.0

In [126]:
np.prod(a)

18977781438000.0

In [128]:
np.max(a,axis=1)

array([95., 82., 45.])

In [129]:
np.min(a,axis=1)

array([31., 22.,  4.])

In [132]:
np.max(a,axis=1)

array([95., 82., 45.])

In [131]:
a

array([[31., 95., 81.],
       [22., 82., 49.],
       [ 4.,  5., 45.]])

In [133]:
np.prod(a,axis=1)

array([238545.,  88396.,    900.])

In [135]:
np.prod(a,axis=0)

array([  2728.,  38950., 178605.])

In [136]:
np.median(a,axis=0)

array([22., 82., 49.])

In [137]:
np.median(a,axis=1)

array([81., 49.,  5.])

In [138]:
np.std(a)

31.933959631993304

In [139]:
np.var(a)

1019.7777777777778

In [140]:
np.sin(a)

array([[-0.40403765,  0.68326171, -0.62988799],
       [-0.00885131,  0.31322878, -0.95375265],
       [-0.7568025 , -0.95892427,  0.85090352]])

In [141]:
np.cos(a)

array([[ 0.91474236,  0.73017356,  0.77668598],
       [-0.99996083,  0.9496777 ,  0.30059254],
       [-0.65364362,  0.28366219,  0.52532199]])